### ISSUE TITLE
Consider making generic-plan a Trusted Language Extension

### ISSUE THREAD

**Issue by michelp** [cybertec-postgresql/generic-plan#1]
AWS recently release a tool called [Trusted Language Extensions](https://github.com/aws/pg_tle) that allow for creating extensions into environments with restricted filesystem access, like RDS.  I think generic-plan is an excellent candidate for being a TLE, and would make installation on RDS a simple code paste.

**Comment by laurenz** [comment]
You can lobby at Amazon if you find it useful.

Actually, I am trying to get native support for that in PostgreSQL, and there is a [patch in the pipeline][commitfest] (will soon be moved to the next commitfest). If you are interested in that, you could review the patch to move it ahead. You don't need C skills for that.


 [commitfest]: https://commitfest.postgresql.org/40/3962/

**Comment by michelp** [comment]
Native support would be even better!  I'm happy to review the patch.  Will close issue.  Thanks!
